### ISSUE TITLE
Error building Unity 5 for iOS

### ISSUE THREAD

**Issue by HimanshuSShephertz** [shephertz/App42_Unity3D_SDK#3]
Missing method UnityEngine.WWWForm::get_headers() in assembly /Users/xxx/New Unity Project

**Comment by HimanshuSShephertz** [comment]
There is some issue with latest version of Unity which you can find below. Once we find the fix from Unity Side, will update the SDK as well. Also, we are trying to get the work around too to get the quick fix.
 
http://issuetracker.unity3d.com/issues/ios-coroutine-never-resumes-if-a-www-request-is-disposed-after-yield-return-www
 
http://issuetracker.unity3d.com/issues/ios-il2cpp-arm64-crashes-most-of-the-times-when-using-httpwebrequest
 
http://issuetracker.unity3d.com/issues/loadfromcacheordownload-crash-on-yield-return-www-object
 
http://issuetracker.unity3d.com/issues/www-post-request-on-webplayer-built-by-unity-5-dot-0-0f2-creates-an-invalid-request
 
http://issuetracker.unity3d.com/issues/unhandled-expection-in-mono-dot-csharp-during-compilation
 
http://issuetracker.unity3d.com/issues/crash-on-opening-scripts-folder
 
http://issuetracker.unity3d.com/issues/ios-il2cpp-build-fails-when-there-is-dll-plugin-in-the-folder-plugins-slash-android
 
Thanks

**Comment by HimanshuSShephertz** [comment]
Hello,

Thanks for your patience. we are releasing App42 Unity SDK 4.0 beta version which is compatible for Unity5 patch2 and above version for following build and can be downloaded from [here](https://github.com/shephertz/App42_Unity3D_SDK/tree/master/4.0%20Beta).

Unity Web Player

Android

iOS (Mono) & iOS (IL2CPP)

Desktop Standalone app

Window Phone

Since Unity 5 still has [issue](http://forum.unity3d.com/threads/unity-5-parse-ios-nsurlerrordomain-error-1012.308569/#post-2040771) with HTTPS  on iOS build, you have to point your build to use our HTTP interface instead of HTTPS as shown below. You have to just set this after App42 API initialize:

App42API.SetBaseURL ("http://ns.api.shephertz.com/cloud/");

Please see our [change log](https://github.com/shephertz/App42_Unity3D_SDK/blob/master/Change%20Log.md) for detail information about feature and bug fixes.

Thanks,

Himanshu Sharma

**Comment by AkshayMShepHertz** [comment]
Solved in App42-Unity3D-SDK version 5.x.
