### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by AhmedHashem** [shephertz/App42_Unity3D_SDK#4]
MissingMethodException: Method not found: 'UnityEngine.WWWForm.get_headers'.
com.shephertz.app42.paas.sdk.csharp.upload.UploadService.UploadFile (System.String name, System.String filePath, System.String fileType, System.String description, App42CallBack callBack)

Unity5 x64 with App42 v 3.2.1

**Comment by AkshayMShepHertz** [comment]
Solved in App42-Unity3D-SDK version 5.x.
